# Generated by Django 2.2.2 on 2019-07-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20190711_0912'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeRolling',
            fields=[
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='todo.Scheme')),
                ('rolling_data', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('calc_date', models.DateField()),
            ],
        ),
    ]
