# Generated by Django 2.2.2 on 2019-11-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_schemerolling'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemestats',
            name='one_year_index_abs_ret',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schemestats',
            name='three_year_index_abs_ret',
            field=models.FloatField(default=0.0),
        ),
    ]
