# Generated by Django 2.2.2 on 2019-06-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190614_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('change_priority', 'Can change priority of a task')]},
        ),
    ]
