# Generated by Django 2.2.2 on 2019-06-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190621_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_category', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(max_length=255)),
                ('scheme_sub_type', models.CharField(max_length=255)),
                ('fund_code', models.CharField(max_length=255)),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_option', models.CharField(max_length=255)),
                ('fund_type', models.CharField(max_length=255)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.AMC')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='nav',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Scheme'),
        ),
    ]
