# Generated by Django 2.2.2 on 2019-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190622_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='fund_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nav',
            unique_together={('scheme', 'nav')},
        ),
        migrations.AlterUniqueTogether(
            name='scheme',
            unique_together={('amc', 'fund_code')},
        ),
    ]
