# Generated by Django 2.2.2 on 2019-06-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190623_0614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nav',
            unique_together={('scheme', 'date')},
        ),
    ]
