# Generated by Django 2.2.2 on 2019-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_mfdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfdownload',
            name='retry',
            field=models.IntegerField(default=0),
        ),
    ]
