# Generated by Django 2.2.2 on 2019-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_mfdownload_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfdownload',
            name='has_data',
            field=models.BooleanField(default=True),
        ),
    ]
