# Generated by Django 2.2.2 on 2019-06-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_mfdownload_has_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='amc_no',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amc',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
