# Generated by Django 2.2.2 on 2019-06-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190627_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='next_amc_no',
            field=models.BooleanField(default=0),
        ),
    ]
