# Generated by Django 2.2.2 on 2019-07-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20190627_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('trade_name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
    ]
