# Generated by Django 2.2.2 on 2019-07-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='index',
            name='close',
        ),
        migrations.RemoveField(
            model_name='index',
            name='open',
        ),
        migrations.RemoveField(
            model_name='index',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='index',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='index',
            name='start_date',
            field=models.DateField(default="2019-01-01"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('pe', models.FloatField()),
                ('pb', models.FloatField()),
                ('div', models.FloatField()),
                ('index', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='todo.Index')),
            ],
            options={
                'unique_together': {('index', 'date')},
            },
        ),
    ]
