# Generated by Django 2.2.2 on 2019-07-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20190701_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexdata',
            unique_together=set(),
        ),
    ]
