# Generated by Django 2.2.2 on 2019-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20190701_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='type',
            field=models.CharField(default='NSE', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='div',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='pb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='pe',
            field=models.FloatField(null=True),
        ),
    ]
