# Generated by Django 2.2.2 on 2019-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20190701_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='index',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together={('name', 'type')},
        ),
    ]
