# Generated by Django 2.2.2 on 2019-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20190711_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='fund_active',
            field=models.BooleanField(default=True),
        ),
    ]
