# Generated by Django 2.2.2 on 2019-07-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_scheme_fund_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='line',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
