# Generated by Django 2.2.2 on 2019-09-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_scheme_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schmeme_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.CharField(max_length=255)),
                ('inception', models.DateField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Scheme')),
            ],
        ),
    ]
