# Generated by Django 2.2.2 on 2019-09-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_schmeme_info'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Scheme_Info',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('benchmark', models.CharField(max_length=255)),
    #             ('inception', models.DateField()),
    #             ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Scheme')),
    #         ],
    #     ),
    #     migrations.AddField(
    #         model_name='amc',
    #         name='logo',
    #         field=models.CharField(max_length=255, null=True),
    #     ),
    #     migrations.DeleteModel(
    #         name='Schmeme_Info',
    #     ),
    # ]
