# Generated by Django 2.2.2 on 2019-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20190919_0906'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='Schmeme_Info',
        #     new_name='Scheme_Info',
        # ),
        # migrations.AddField(
        #     model_name='amc',
        #     name='logo',
        #     field=models.CharField(max_length=255, null=True),
        # ),
        migrations.AddField(
            model_name='scheme',
            name='clean_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
