# Generated by Django 2.2.2 on 2019-08-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('processed_file_name', models.TextField()),
                ('password', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_error', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAdminLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
        ),
    ]
