# Generated by Django 2.2.2 on 2019-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioadmin',
            name='is_processed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
