# Generated by Django 2.2.2 on 2019-08-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_scheme_line'),
        ('portfolio', '0002_portfolioadmin_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('mobile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.AMC')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.TextField()),
                ('portfolio_amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioAMC')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFolioTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_type', models.TextField()),
                ('trx_name', models.TextField()),
                ('trx_date', models.DateField()),
                ('trx_amount', models.FloatField()),
                ('trx_price_unit', models.FloatField()),
                ('trx_unit', models.FloatField()),
                ('unit_balance', models.FloatField()),
                ('trx_amount_type', models.TextField()),
                ('portfolio_folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioFolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFolioFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_text', models.TextField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Scheme')),
                ('portfolio_folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioFolio')),
            ],
        ),
    ]
