# Generated by Django 2.2.2 on 2019-08-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_portfolioamc_portfoliofolio_portfoliofoliofund_portfoliofoliotrx'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioadminlogs',
            name='portfolio_admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioAdmin'),
            preserve_default=False,
        ),
    ]
