# Generated by Django 2.2.2 on 2019-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioadminlogs_portfolio_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliofoliofund',
            name='fund',
        ),
        migrations.AddField(
            model_name='portfoliofoliofund',
            name='fund_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
