# Generated by Django 2.2.2 on 2019-08-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190813_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofoliofund',
            name='fund_id',
            field=models.TextField(),
        ),
    ]
