# Generated by Django 2.2.2 on 2019-07-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0016_auto_20190701_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme_Portfolio_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('coupon', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
                ('percent', models.CharField(max_length=255)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Scheme')),
            ],
        ),
    ]
