# Generated by Django 2.2.2 on 2019-07-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_amc_portfolio_process_amc_portfolio_process_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc_portfolio_process',
            name='final_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='amc_portfolio_process',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
