# Generated by Django 2.2.2 on 2019-07-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_auto_20190707_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme_Portfolio_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('date', models.DateField()),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Scheme_Portfolio_Url',
        ),
        migrations.AlterField(
            model_name='scheme_portfolio',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.Scheme_Portfolio_Data'),
        ),
    ]
