# Generated by Django 2.2.2 on 2019-08-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_scheme_line'),
        ('amc', '0007_scheme_aum_scheme_aum_process_scheme_aum_process_log'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheme_portfolio_data',
            unique_together={('scheme', 'date')},
        ),
    ]
