# Generated by Django 2.2.2 on 2019-09-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0008_auto_20190802_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme_aum_process_log',
            name='process',
        ),
        migrations.DeleteModel(
            name='Scheme_AUM_Process',
        ),
        migrations.DeleteModel(
            name='Scheme_AUM_Process_Log',
        ),
    ]
